services:
  mongo:
    image: mongo:7
    container_name: ingestion-mongo
    ports:
      - "27017:27017"
    command: ["mongod","--replSet","rs0","--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 3s
      retries: 20

  mongo-init:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: >
      bash -lc "mongosh --host mongo:27017 --eval 'rs.initiate({_id:"rs0",members:[{_id:0,host:"mongo:27017"}]})' || true"
